input {
  file {
    # Ajusta el nombre exacto del archivo si no se llama "customers.csv"
    path => "C:/Users/Steeven/Documents/USFQ/Ingenieria de Datos/Northwind/customers.csv"
    mode => "read"
    file_completed_action => "log"
    file_completed_log_path => "./customers_completed.log"
    start_position => "beginning"
  }
}

filter {
  csv {
    separator => ","
    skip_header => true
    columns => [
      "customerID", "companyName", "contactName", "contactTitle",
      "address", "city", "region", "postalCode", "country", "phone", "fax"
    ]
  }

  # Limpieza de metadata que agrega el input file, no la necesitamos en Elasticsearch
  mutate {
    remove_field => ["message", "path", "host", "@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "data_customers_csv"
    document_id => "%{customerID}"
  }

  # Para ver en consola lo que se va cargando
  stdout {
    codec => json_lines
  }
}
