input {
  jdbc {
    # PostgreSQL JDBC Connection String (northwind_pg = tu base fuente)
    jdbc_connection_string => "jdbc:postgresql://127.0.0.1:5432/northwind_pg"
    jdbc_user => "miuser"
    jdbc_password => "miclave"
    jdbc_driver_library => "./postgresql-42.7.13.jar"
    jdbc_driver_class => "org.postgresql.Driver"

    # Solo trae filas con productid mayor al último ya procesado (near real-time incremental)
    statement => "SELECT * FROM products WHERE productid > :sql_last_value ORDER BY productid ASC"
    use_column_value => true
    tracking_column => "productid"
    tracking_column_type => "numeric"

    # Archivo donde Logstash guarda el último productid procesado (distinto al de orders)
    last_run_metadata_path => "./.logstash_jdbc_last_run_products"

    # Revisa cada 10 segundos si hay productos nuevos
    schedule => "*/10 * * * * *"
  }
}

filter {
  mutate {
    remove_field => ["@version"]
  }
}

output {
  elasticsearch {
    hosts => ["http://127.0.0.1:9200"]
    index => "data_products_postgres"
    document_id => "%{productid}"
  }

  # Para ver en consola lo que va llegando mientras haces la demo
  stdout {
    codec => json_lines
  }
}
